# Generated by Django 3.0.7 on 2020-06-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20200611_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='socket_room_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
